-- Creating tables for final project
CREATE TABLE weekly_deaths (
	Data_As_Of VARCHAR NOT NULL,
	START_DATE VARCHAR NOT NULL,
	END_DATE VARCHAR NOT NULL,
	GROUP1 VARCHAR NOT NULL,
	YEAR1 VARCHAR NOT NULL,
	MONTH1 VARCHAR NOT NULL,
	MMWR_Week VARCHAR NOT NULL,
	Week_Ending_Date VARCHAR NOT NULL,
	HHS_Region VARCHAR NOT NULL,
	Race VARCHAR NOT NULL,
	age_group VARCHAR NOT NULL,
	COVID_deaths INT,
	Total_Deaths INT,
	Footnote VARCHAR
);